import React, { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useToast } from '../Toast';
import './ProfileSections.css';

export default function FriendsTab({ friends = [], isOwnProfile }) {
  const navigate = useNavigate(); const { showToast } = useToast(); const [subTab, setSubTab] = useState('all'); const [query, setQuery] = useState('');
  const filtered = useMemo(() => friends.filter(friend => friend.name?.toLowerCase().includes(query.toLowerCase())), [friends, query]);
  return <div className="profile-section-main"><div className="section-head"><h2>বন্ধুরা / Friends <small>· {friends.length}</small></h2>{isOwnProfile && <div><button className="section-secondary" onClick={() => navigate('/friends')}>বন্ধুর অনুরোধ / Friend Requests</button> <button className="section-secondary" onClick={() => navigate('/friends')}>বন্ধু খুঁজুন / Find Friends</button></div>}</div><input className="profile-search" value={query} onChange={e => setQuery(e.target.value)} placeholder="বন্ধু খুঁজুন... / Search friends..." /><div className="section-tabs"><button className={`section-tab ${subTab === 'all' ? 'active' : ''}`} onClick={() => setSubTab('all')}>বন্ধুরা / Friends</button><button className={`section-tab ${subTab === 'recent' ? 'active' : ''}`} onClick={() => setSubTab('recent')}>সম্প্রতি যোগ হয়েছে / Recently Added</button><button className={`section-tab ${subTab === 'birthdays' ? 'active' : ''}`} onClick={() => setSubTab('birthdays')}>জন্মদিন / Birthdays</button><button className="section-tab" onClick={() => showToast('শীঘ্রই আসছে / Coming soon')}>ফলোয়ার / Followers</button><button className="section-tab" onClick={() => showToast('শীঘ্রই আসছে / Coming soon')}>ফলোয়িং / Following</button></div>{subTab !== 'all' ? <div className="section-empty">এই ফিল্টারের তথ্য এখনো নেই / No data for this filter yet</div> : <div className="friend-section-grid">{filtered.map(friend => <div className="friend-section-card" key={friend.id} onClick={() => navigate(`/profile/${friend.id}`)}>{(friend.avatarUrl || friend.profile_photo_url || friend.avatar_url) ? <img src={friend.avatarUrl || friend.profile_photo_url || friend.avatar_url} alt={friend.name} /> : <div className="friend-section-avatar">{friend.name?.[0] || '?'}</div>}<strong>{friend.name}</strong></div>)}</div>}</div>;
}
